INSERT INTO DISTANCES VALUES(0,'Angel Stadium','Petco Park',110);
INSERT INTO DISTANCES VALUES(1,'Angel Stadium','Dodger Stadium',50);
INSERT INTO DISTANCES VALUES(2,'Busch Stadium','Minute Maid Park',680);
INSERT INTO DISTANCES VALUES(3,'Busch Stadium','Great American Ball Park',310);
INSERT INTO DISTANCES VALUES(4,'Busch Stadium','Target Field',465);
INSERT INTO DISTANCES VALUES(5,'Busch Stadium','Kauffman Stadium',235);
INSERT INTO DISTANCES VALUES(6,'Chase Field','Coors Field',580);
INSERT INTO DISTANCES VALUES(7,'Chase Field','Globe Life Park in Arlington',870);
INSERT INTO DISTANCES VALUES(8,'Chase Field','Minute Maid Park',1115);
INSERT INTO DISTANCES VALUES(9,'Chase Field','Oakland–Alameda County Coliseum',650);
INSERT INTO DISTANCES VALUES(10,'Chase Field','Petco Park',300);
INSERT INTO DISTANCES VALUES(11,'Citi Field','Fenway Park',195);
INSERT INTO DISTANCES VALUES(12,'Citi Field','Yankee Stadium',50);
INSERT INTO DISTANCES VALUES(13,'Citizens Bank Park','Yankee Stadium',80);
INSERT INTO DISTANCES VALUES(14,'Citizens Bank Park','Oriole Park at Camden Yards',90);
INSERT INTO DISTANCES VALUES(15,'Comerica Park','Guaranteed Rate Field',240);
INSERT INTO DISTANCES VALUES(16,'Comerica Park','Rogers Centre',210);
INSERT INTO DISTANCES VALUES(17,'Comerica Park','Progressive Field',90);
INSERT INTO DISTANCES VALUES(18,'Coors Field','Kauffman Stadium',560);
INSERT INTO DISTANCES VALUES(19,'Coors Field','Globe Life Park in Arlington',650);
INSERT INTO DISTANCES VALUES(20,'Coors Field','Chase Field',580);
INSERT INTO DISTANCES VALUES(21,'Coors Field','Petco Park',830);
INSERT INTO DISTANCES VALUES(22,'Dodger Stadium','Angel Stadium',50);
INSERT INTO DISTANCES VALUES(23,'Dodger Stadium','Target Field',1500);
INSERT INTO DISTANCES VALUES(24,'Dodger Stadium','Oakland–Alameda County Coliseum',340);
INSERT INTO DISTANCES VALUES(25,'Fenway Park','Citi Field',195);
INSERT INTO DISTANCES VALUES(26,'Fenway Park','Marlins Park',1255);
INSERT INTO DISTANCES VALUES(27,'Fenway Park','Rogers Centre',430);
INSERT INTO DISTANCES VALUES(28,'Globe Life Park in Arlington','Chase Field',870);
INSERT INTO DISTANCES VALUES(29,'Globe Life Park in Arlington','Kauffman Stadium',460);
INSERT INTO DISTANCES VALUES(30,'Globe Life Park in Arlington','SunTrust Park',740);
INSERT INTO DISTANCES VALUES(31,'Globe Life Park in Arlington','Minute Maid Park',230);
INSERT INTO DISTANCES VALUES(32,'Globe Life Park in Arlington','Coors Field',650);
INSERT INTO DISTANCES VALUES(33,'Great American Ball Park','PNC Park',260);
INSERT INTO DISTANCES VALUES(34,'Great American Ball Park','Progressive Field',225);
INSERT INTO DISTANCES VALUES(35,'Great American Ball Park','Guaranteed Rate Field',250);
INSERT INTO DISTANCES VALUES(36,'Great American Ball Park','Tropicana Field',790);
INSERT INTO DISTANCES VALUES(37,'Great American Ball Park','SunTrust Park',375);
INSERT INTO DISTANCES VALUES(38,'Great American Ball Park','Busch Stadium',310);
INSERT INTO DISTANCES VALUES(39,'Guaranteed Rate Field','Comerica Park',240);
INSERT INTO DISTANCES VALUES(40,'Guaranteed Rate Field','Great American Ball Park',250);
INSERT INTO DISTANCES VALUES(41,'Guaranteed Rate Field','Wrigley Field',50);
INSERT INTO DISTANCES VALUES(42,'Kauffman Stadium','Busch Stadium',235);
INSERT INTO DISTANCES VALUES(43,'Kauffman Stadium','Globe Life Park in Arlington',460);
INSERT INTO DISTANCES VALUES(44,'Kauffman Stadium','Wrigley Field',415);
INSERT INTO DISTANCES VALUES(45,'Kauffman Stadium','Coors Field',560);
INSERT INTO DISTANCES VALUES(46,'Marlins Park','SunTrust Park',600);
INSERT INTO DISTANCES VALUES(47,'Marlins Park','Tropicana Field',210);
INSERT INTO DISTANCES VALUES(48,'Marlins Park','Nationals Park',930);
INSERT INTO DISTANCES VALUES(49,'Marlins Park','Fenway Park',1255);
INSERT INTO DISTANCES VALUES(50,'Marlins Park','Minute Maid Park',965);
INSERT INTO DISTANCES VALUES(51,'Miller Park','Rogers Centre',430);
INSERT INTO DISTANCES VALUES(52,'Miller Park','Wrigley Field',80);
INSERT INTO DISTANCES VALUES(53,'Miller Park','Target Field',300);
INSERT INTO DISTANCES VALUES(54,'Minute Maid Park','Globe Life Park in Arlington',230);
INSERT INTO DISTANCES VALUES(55,'Minute Maid Park','Tropicana Field',790);
INSERT INTO DISTANCES VALUES(56,'Minute Maid Park','Marlins Park',965);
INSERT INTO DISTANCES VALUES(57,'Minute Maid Park','Busch Stadium',680);
INSERT INTO DISTANCES VALUES(58,'Minute Maid Park','Chase Field',1115);
INSERT INTO DISTANCES VALUES(59,'Nationals Park','Oriole Park at Camden Yards',50);
INSERT INTO DISTANCES VALUES(60,'Nationals Park','PNC Park',195);
INSERT INTO DISTANCES VALUES(61,'Nationals Park','SunTrust Park',560);
INSERT INTO DISTANCES VALUES(62,'Nationals Park','Marlins Park',930);
INSERT INTO DISTANCES VALUES(63,'Oakland–Alameda County Coliseum','Oracle Park',50);
INSERT INTO DISTANCES VALUES(64,'Oakland–Alameda County Coliseum','Dodger Stadium',340);
INSERT INTO DISTANCES VALUES(65,'Oakland–Alameda County Coliseum','Chase Field',650);
INSERT INTO DISTANCES VALUES(66,'Oracle Park','Safeco Field',680);
INSERT INTO DISTANCES VALUES(67,'Oracle Park','Oakland–Alameda County Coliseum',50);
INSERT INTO DISTANCES VALUES(68,'Oriole Park at Camden Yards','Nationals Park',50);
INSERT INTO DISTANCES VALUES(69,'Oriole Park at Camden Yards','Citizens Bank Park',90);
INSERT INTO DISTANCES VALUES(70,'Petco Park','Coors Field',830);
INSERT INTO DISTANCES VALUES(71,'Petco Park','Chase Field',300);
INSERT INTO DISTANCES VALUES(72,'Petco Park','Angel Stadium',110);
INSERT INTO DISTANCES VALUES(73,'PNC Park','Nationals Park',195);
INSERT INTO DISTANCES VALUES(74,'PNC Park','Rogers Centre',225);
INSERT INTO DISTANCES VALUES(75,'PNC Park','Progressive Field',115);
INSERT INTO DISTANCES VALUES(76,'PNC Park','Great American Ball Park',260);
INSERT INTO DISTANCES VALUES(77,'PNC Park','Yankee Stadium',315);
INSERT INTO DISTANCES VALUES(78,'Progressive Field','PNC Park',115);
INSERT INTO DISTANCES VALUES(79,'Progressive Field','Comerica Park',90);
INSERT INTO DISTANCES VALUES(80,'Progressive Field','Great American Ball Park',225);
INSERT INTO DISTANCES VALUES(81,'Rogers Centre','PNC Park',225);
INSERT INTO DISTANCES VALUES(82,'Rogers Centre','Miller Park',430);
INSERT INTO DISTANCES VALUES(83,'Rogers Centre','Comerica Park',210);
INSERT INTO DISTANCES VALUES(84,'Rogers Centre','Fenway Park',430);
INSERT INTO DISTANCES VALUES(85,'Rogers Centre','Safeco Field',2070);
INSERT INTO DISTANCES VALUES(86,'Safeco Field','Rogers Centre',2070);
INSERT INTO DISTANCES VALUES(87,'Safeco Field','Target Field',1390);
INSERT INTO DISTANCES VALUES(88,'Safeco Field','Oracle Park',680);
INSERT INTO DISTANCES VALUES(89,'SunTrust Park','Great American Ball Park',375);
INSERT INTO DISTANCES VALUES(90,'SunTrust Park','Nationals Park',560);
INSERT INTO DISTANCES VALUES(91,'SunTrust Park','Marlins Park',600);
INSERT INTO DISTANCES VALUES(92,'SunTrust Park','Globe Life Park in Arlington',740);
INSERT INTO DISTANCES VALUES(93,'Target Field','Dodger Stadium',1500);
INSERT INTO DISTANCES VALUES(94,'Target Field','Busch Stadium',465);
INSERT INTO DISTANCES VALUES(95,'Target Field','Miller Park',300);
INSERT INTO DISTANCES VALUES(96,'Target Field','Safeco Field',1390);
INSERT INTO DISTANCES VALUES(97,'Tropicana Field','Great American Ball Park',790);
INSERT INTO DISTANCES VALUES(98,'Tropicana Field','Marlins Park',210);
INSERT INTO DISTANCES VALUES(99,'Tropicana Field','Minute Maid Park',790);
INSERT INTO DISTANCES VALUES(100,'Wrigley Field','Guaranteed Rate Field',50);
INSERT INTO DISTANCES VALUES(101,'Wrigley Field','Miller Park',80);
INSERT INTO DISTANCES VALUES(102,'Wrigley Field','Kauffman Stadium',415);
INSERT INTO DISTANCES VALUES(103,'Yankee Stadium','PNC Park',315);
INSERT INTO DISTANCES VALUES(104,'Yankee Stadium','Citizens Bank Park',80);
INSERT INTO DISTANCES VALUES(105,'Yankee Stadium','Citi Field',50);
