INSERT INTO SOUVENIRS VALUES(0,'Arizona Diamondbacks','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(1,'Arizona Diamondbacks','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(2,'Arizona Diamondbacks','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(3,'Arizona Diamondbacks','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(4,'Arizona Diamondbacks','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(5,'Atlanta Braves','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(6,'Atlanta Braves','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(7,'Atlanta Braves','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(8,'Atlanta Braves','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(9,'Atlanta Braves','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(10,'Baltimore Orioles','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(11,'Baltimore Orioles','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(12,'Baltimore Orioles','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(13,'Baltimore Orioles','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(14,'Baltimore Orioles','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(15,'Boston Red Sox','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(16,'Boston Red Sox','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(17,'Boston Red Sox','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(18,'Boston Red Sox','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(19,'Boston Red Sox','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(20,'Chicago Cubs','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(21,'Chicago Cubs','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(22,'Chicago Cubs','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(23,'Chicago Cubs','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(24,'Chicago Cubs','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(25,'Chicago White Sox','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(26,'Chicago White Sox','Baseball bat', 89.39);
INSERT INTO SOUVENIRS VALUES(27,'Chicago White Sox','Team pennant', 17.99);
INSERT INTO SOUVENIRS VALUES(28,'Chicago White Sox','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(29,'Chicago White Sox','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(30,'Cincinnati Reds','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(31,'Cincinnati Reds','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(32,'Cincinnati Reds','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(33,'Cincinnati Reds','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(34,'Cincinnati Reds','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(35,'Cleveland Indians','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(36,'Cleveland Indians','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(37,'Cleveland Indians','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(38,'Cleveland Indians','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES (39,'Cleveland Indians','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(40,'Colorado Rockies','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(41,'Colorado Rockies','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(42,'Colorado Rockies','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(43,'Colorado Rockies','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(44,'Colorado Rockies','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(45,'Detroit Tigers','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(46,'Detroit Tigers','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(47,'Detroit Tigers','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(48,'Detroit Tigers','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(49,'Detroit Tigers','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(50,'Houston Astros','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(51,'Houston Astros','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(52,'Houston Astros','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(53,'Houston Astros','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(54,'Houston Astros','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(55,'Kansas City Royals','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(56,'Kansas City Royals','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(57,'Kansas City Royals','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(58,'Kansas City Royals','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(59,'Kansas City Royals','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(60,'Los Angeles Angels','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(61,'Los Angeles Angels','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(62,'Los Angeles Angels','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(63,'Los Angeles Angels','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(64,'Los Angeles Angels','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(65,'Los Angeles Dodgers','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(66,'Los Angeles Dodgers','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(67,'Los Angeles Dodgers','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(68,'Los Angeles Dodgers','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(69,'Los Angeles Dodgers','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(70,'Miami Marlins','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(71,'Miami Marlins','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(72,'Miami Marlins','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(73,'Miami Marlins','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(74,'Miami Marlins','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(75,'Milwaukee Brewers','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(76,'Milwaukee Brewers','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(77,'Milwaukee Brewers','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(78,'Milwaukee Brewers','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(79,'Milwaukee Brewers','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(80,'Minnesota Twins','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(81,'Minnesota Twins','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(82,'Minnesota Twins','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(83,'Minnesota Twins','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(84,'Minnesota Twins','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(85,'New York Mets','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(86,'New York Mets','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(87,'New York Mets','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(88,'New York Mets','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(89,'New York Mets','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(90,'New York Yankees','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(91,'New York Yankees','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(92,'New York Yankees','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(93,'New York Yankees','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(94,'New York Yankees','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(95,'Oakland Athletics','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(96,'Oakland Athletics','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(97,'Oakland Athletics','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(98,'Oakland Athletics','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(99,'Oakland Athletics','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(100,'Philadelphia Phillies','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(101,'Philadelphia Phillies','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(102,'Philadelphia Phillies','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(103,'Philadelphia Phillies','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(104,'Philadelphia Phillies','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(105,'Pittsburgh Pirates','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(106,'Pittsburgh Pirates','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(107,'Pittsburgh Pirates','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(108,'Pittsburgh Pirates','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(109,'Pittsburgh Pirates','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(110,'San Diego Padres','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(111,'San Diego Padres','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(112,'San Diego Padres','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(113,'San Diego Padres','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(114,'San Diego Padres','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(115,'San Francisco Giants','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(116,'San Francisco Giants','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(117,'San Francisco Giants','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(118,'San Francisco Giants','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(119,'San Francisco Giants','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(120,'Seattle Mariners','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(121,'Seattle Mariners','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(122,'Seattle Mariners','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(123,'Seattle Mariners','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(124,'Seattle Mariners','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(125,'St. Louis Cardinals','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(126,'St. Louis Cardinals','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(127,'St. Louis Cardinals','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(128,'St. Louis Cardinals','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(129,'St. Louis Cardinals','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(130,'Tampa Bay Rays','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(131,'Tampa Bay Rays','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(132,'Tampa Bay Rays','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(133,'Tampa Bay Rays','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(134,'Tampa Bay Rays','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(135,'Texas Rangers','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(136,'Texas Rangers','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(137,'Texas Rangers','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(138,'Texas Rangers','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(139,'Texas Rangers','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(140,'Toronto Blue Jays','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(141,'Toronto Blue Jays','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(142,'Toronto Blue Jays','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(143,'Toronto Blue Jays','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(144,'Toronto Blue Jays','Team jersey',199.99);
INSERT INTO SOUVENIRS VALUES(145,'Washington Nationals','Baseball cap',19.99);
INSERT INTO SOUVENIRS VALUES(146,'Washington Nationals','Baseball bat',89.39);
INSERT INTO SOUVENIRS VALUES(147,'Washington Nationals','Team pennant',17.99);
INSERT INTO SOUVENIRS VALUES(148,'Washington Nationals','Autographed baseball',29.99);
INSERT INTO SOUVENIRS VALUES(149,'Washington Nationals','Team jersey',199.99);